Actions now does local install of cluacov
D'oh! I even made sure the cache got the local build artifacts from
luarocks, but forgot to make it a local install:

https://github.com/2ndBillingCycle/specialsounds/runs/458935020?check_suite_focus=true#step:5:12

    Error: Your user does not have write permissions in /usr/local/lib/luarocks/rocks
    -- you may want to run as a privileged user or use your local tree with --local.
    ##[error]Process completed with exit code 2.